package com.techelevator.dao;
import com.techelevator.model.Applicant;
import com.techelevator.dao.JdbcApplicantDao;
import com.techelevator.dao.JdbcShelterApplicationDao; // Import the verification DAO
import com.techelevator.model.ShelterApplication;     // Import the model object for verification
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import static org.junit.jupiter.api.Assertions.*;

public class JdbcApplicantDaoTest extends BaseDaoTest {

    protected static final Applicant USER_1 = new Applicant("Tom", "Anderson",
            "tom@te.org", "2104440000");
    protected static final Applicant USER_2 = new Applicant("Peggy", "Kachevas",
            "peggy@te.org", "9029993333");
    protected static final Applicant USER_3 = new Applicant("Andy", "Chong",
            "andy@te.org", "5554449090");


        private JdbcApplicantDao sut;

        private JdbcShelterApplicationDao shelterAppDao;

        @BeforeEach
        public void setup() {
            JdbcTemplate jdbcTemplate = new JdbcTemplate(dataSource);

            sut = new JdbcApplicantDao(jdbcTemplate);

            shelterAppDao = new JdbcShelterApplicationDao(jdbcTemplate);
        }

        @Test
        void submitApplication_shouldInsertNewApplicantAndReturnNewId() {

            Applicant applicantToSubmit = new Applicant(
                    USER_1.getFirstName(),
                    USER_1.getLastName(),
                    USER_1.getEmail(),
                    USER_1.getPhoneNumber()
            );



            // ACT: Call the method under test to insert the record.
            Applicant submittedApplicant = sut.submitApplication(applicantToSubmit);

            // ASSERT (Part 1: Check the returned Applicant object)
            assertNotNull(submittedApplicant, "The returned applicant should not be null.");
            Integer newAppId = submittedApplicant.getApplicationId();
            assertNotNull(newAppId, "The application ID must be generated by the database.");

            // Check returned data integrity
            assertEquals(applicantToSubmit.getFirstName(), submittedApplicant.getFirstName(), "First name mismatch in returned object.");


            // ASSERT (Part 2: Verify data in the database using the verification DAO)

            // Retrieve the record using the separate ShelterApplicationDao
            ShelterApplication retrievedApp = shelterAppDao.findById(newAppId);

            assertNotNull(retrievedApp, "The application should be retrievable from the database using the new ID.");

            // Verify core application details
            assertEquals(newAppId, retrievedApp.getApplicationId(), "Retrieved ID must match the new ID.");

            // Verification of data that was carried over from the Applicant model
            assertEquals(applicantToSubmit.getFirstName(), retrievedApp.getFirstName(), "Retrieved first name mismatch.");
            // ... (Check other fields like lastName, email, phoneNumber)

            // Crucial verification: Check the default status set by the SQL INSERT.
            assertEquals("pending", retrievedApp.getStatus(), "Default status should be 'pending'.");
        }
    }